In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
%matplotlib inline

In [3]:
df=pd.read_csv(r"C:\Users\LENOVO\Downloads\Weather_Data.csv")
df.head()

Date  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0  2/1/2008     19.5     22.4      15.6          6.2       0.0           W   
1  2/2/2008     19.5     25.6       6.0          3.4       2.7           W   
2  2/3/2008     21.6     24.5       6.6          2.4       0.1           W   
3  2/4/2008     20.2     22.8      18.8          2.2       0.0           W   
4  2/5/2008     19.7     25.7      77.4          4.8       0.0           W   

   WindGustSpeed WindDir9am WindDir3pm  ...  Humidity9am  Humidity3pm  \
0             41          S        SSW  ...           92           84   
1             41          W          E  ...           83           73   
2             41        ESE        ESE  ...           88           86   
3             41        NNE          E  ...           83           90   
4             41        NNE          W  ...           88           74   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1017.6       1017.4         8         8     20.7     20.9        Yes   
1       1017.9       1016.4         7         7     22.4     24.8        Yes   
2       1016.7       1015.6         7         8     23.5     23.0        Yes   
3       1014.2       1011.8         8         8     21.4     20.9        Yes   
4       1008.3       1004.8         8         8     22.5     25.5        Yes   

   RainTomorrow  
0           Yes  
1           Yes  
2           Yes  
3           Yes  
4           Yes  

[5 rows x 22 columns]

In [5]:
df.shape

(3271, 22)

#### Data Preprocessing

In [9]:
df_sydney_processed = pd.get_dummies(data=df, columns=['RainToday', 'WindGustDir', 'WindDir9am', 'WindDir3pm'])
df_sydney_processed.replace(['No', 'Yes'], [0,1], inplace=True)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_20852\2041156061.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_sydney_processed.replace(['No', 'Yes'], [0,1], inplace=True)


In [11]:
df_sydney_processed

Date  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0      2/1/2008     19.5     22.4      15.6          6.2       0.0   
1      2/2/2008     19.5     25.6       6.0          3.4       2.7   
2      2/3/2008     21.6     24.5       6.6          2.4       0.1   
3      2/4/2008     20.2     22.8      18.8          2.2       0.0   
4      2/5/2008     19.7     25.7      77.4          4.8       0.0   
...         ...      ...      ...       ...          ...       ...   
3266  6/21/2017      8.6     19.6       0.0          2.0       7.8   
3267  6/22/2017      9.3     19.2       0.0          2.0       9.2   
3268  6/23/2017      9.4     17.7       0.0          2.4       2.7   
3269  6/24/2017     10.1     19.3       0.0          1.4       9.3   
3270  6/25/2017      7.6     19.3       0.0          3.4       9.4   

      WindGustSpeed  WindSpeed9am  WindSpeed3pm  Humidity9am  ...  \
0                41            17            20           92  ...   
1                41             9            13           83  ...   
2                41            17             2           88  ...   
3                41            22            20           83  ...   
4                41            11             6           88  ...   
...             ...           ...           ...          ...  ...   
3266             37            22            20           73  ...   
3267             30            20             7           78  ...   
3268             24            15            13           85  ...   
3269             43            17            19           56  ...   
3270             35            13            13           73  ...   

      WindDir3pm_NNW  WindDir3pm_NW  WindDir3pm_S  WindDir3pm_SE  \
0              False          False         False          False   
1              False          False         False          False   
2              False          False         False          False   
3              False          False         False          False   
4              False          False         False          False   
...              ...            ...           ...            ...   
3266           False          False         False          False   
3267           False          False         False          False   
3268           False          False         False          False   
3269           False          False         False          False   
3270           False          False         False          False   

      WindDir3pm_SSE  WindDir3pm_SSW  WindDir3pm_SW  WindDir3pm_W  \
0              False            True          False         False   
1              False           False          False         False   
2              False           False          False         False   
3              False           False          False         False   
4              False           False          False          True   
...              ...             ...            ...           ...   
3266            True           False          False         False   
3267           False           False          False         False   
3268           False           False          False         False   
3269           False           False          False          True   
3270           False           False          False          True   

      WindDir3pm_WNW  WindDir3pm_WSW  
0              False           False  
1              False           False  
2              False           False  
3              False           False  
4              False           False  
...              ...             ...  
3266           False           False  
3267           False           False  
3268           False           False  
3269           False           False  
3270           False           False  

[3271 rows x 68 columns]

#### Training and Test data

In [15]:
df_sydney_processed.drop('Date',axis=1,inplace=True)

In [18]:
df_sydney_processed = df_sydney_processed.astype(float)

In [20]:
features = df_sydney_processed.drop(columns='RainTomorrow', axis=1)
Y = df_sydney_processed['RainTomorrow']

In [24]:
Y

0       1.0
1       1.0
2       1.0
3       1.0
4       1.0
       ... 
3266    0.0
3267    0.0
3268    0.0
3269    0.0
3270    0.0
Name: RainTomorrow, Length: 3271, dtype: float64

In [30]:
x_train,x_test,y_train,y_test=train_test_split(features,Y,test_size=0.2,random_state=10)
print("TRAINING SET:",x_train.shape, y_train.shape)
print("TESTING SET:",x_test.shape, y_test.shape)

TRAINING SET: (2616, 66) (2616,)
TESTING SET: (655, 66) (655,)


#### Modelling for Linear Regression

In [38]:
from sklearn.linear_model import LinearRegression
regr=LinearRegression()
regr.fit(x_train,y_train)

LinearRegression()

In [40]:
predictions=regr.predict(x_test)
predictions

array([ 1.31809235e-01,  2.76157379e-01,  9.78160858e-01,  2.87452698e-01,
        1.32392883e-01,  4.60456848e-01,  3.56792450e-01,  8.56433868e-01,
        6.75003052e-01,  3.82423401e-02,  4.80270386e-03,  2.81208038e-01,
        3.39076996e-01,  7.80906677e-02,  6.26144409e-02,  5.64426422e-01,
       -6.15615845e-02,  5.24158478e-01,  1.53717041e-01,  3.59683990e-01,
        6.05354309e-02,  9.03549194e-01,  4.67319489e-01,  2.03361511e-01,
       -7.10487366e-02,  3.83892059e-01,  5.36094666e-01, -2.28652954e-02,
        6.40060425e-01, -9.56687927e-02,  3.78097534e-01,  1.20269775e-01,
       -1.81503296e-02,  5.53894043e-02,  5.63556671e-01,  1.06301498e+00,
       -6.75582886e-03,  5.14404297e-01, -8.83712769e-02,  6.91871643e-02,
        2.44827271e-02,  8.71700287e-01,  2.44621277e-01,  3.94725800e-01,
        2.67524719e-01,  4.46777344e-01, -4.75730896e-02,  1.89430237e-01,
        7.76588440e-01,  1.57726288e-01,  3.93295288e-03, -5.19943237e-02,
        2.07324982e-01, -

In [62]:
from sklearn.metrics import r2_score
LinearRegression_MAE=np.mean(np.absolute(predictions-y_test))
LinearRegression_MSE=np.mean((predictions-y_test)**2)
LinearRegression_R2=r2_score(predictions,y_test)

#### Evaluation for Linear Regression

In [64]:
metrics_data = {'Metric': ['Mean Absolute Error (MAE)', 'Mean Squared Error (MSE)', 'R-squared (R2)'],'Value': [LinearRegression_MAE, LinearRegression_MSE, LinearRegression_R2]}
output=pd.DataFrame(metrics_data)
output

Metric     Value
0  Mean Absolute Error (MAE)  0.256319
1   Mean Squared Error (MSE)  0.115722
2             R-squared (R2) -0.384792

#### MODELLING FOR KNN

In [70]:
from sklearn.neighbors import KNeighborsClassifier
k=4
neigh=KNeighborsClassifier(n_neighbors=k).fit(x_train,y_train)
neigh

KNeighborsClassifier(n_neighbors=4)

In [72]:
predictions=neigh.predict(x_test)
predictions

array([0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
       1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0.

#### Evaluation for KNN

In [84]:
from sklearn import metrics
from sklearn.metrics import jaccard_score
from sklearn.metrics import f1_score
KNN_Accuracy_Score = metrics.accuracy_score(y_test,predictions)
KNN_JaccardIndex = jaccard_score(y_test,predictions)
KNN_F1_Score = f1_score(y_test,predictions)
output={"Metrics":["Accuracy Score","Jaccard Score","F1 Score"],"Values":[KNN_Accuracy_Score, KNN_JaccardIndex, KNN_F1_Score]}
output=pd.DataFrame(output)
output

Metrics    Values
0  Accuracy Score  0.818321
1   Jaccard Score  0.425121
2        F1 Score  0.596610

#### MODELLING FOR DECISION TREE

In [89]:
from sklearn.tree import DecisionTreeClassifier
tree=DecisionTreeClassifier(criterion="entropy",max_depth=4)
tree.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=4)

In [91]:
predictions=tree.predict(x_test)
predictions

array([0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
       1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 0., 0.

In [95]:
Tree_Accuracy_Score = metrics.accuracy_score(y_test,predictions)
Tree_JaccardIndex = jaccard_score(y_test,predictions)
Tree_F1_Score = f1_score(y_test,predictions)
output={"Metrics":["Accuracy Score","Jaccard Score","F1 Score"],"Values":[Tree_Accuracy_Score, Tree_JaccardIndex, Tree_F1_Score]}
output=pd.DataFrame(output)
output

Metrics    Values
0  Accuracy Score  0.818321
1   Jaccard Score  0.480349
2        F1 Score  0.648968

#### Modelling for Logistic Regression

In [98]:
x_train,x_test,y_train,y_test=train_test_split(features,Y,test_size=0.2,random_state=1)
print ('Train set:', x_train.shape,  y_train.shape)
print ('Test set:', x_test.shape,  y_test.shape)

Train set: (2616, 66) (2616,)
Test set: (655, 66) (655,)


In [102]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(C=0.01, solver='liblinear').fit(x_train,y_train)
LR

LogisticRegression(C=0.01, solver='liblinear')

In [106]:
predictions=LR.predict(x_test)
predictions

array([0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1.,
       1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1.,
       0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
       1., 0., 1., 1., 0.

In [108]:
predict_proba=LR.predict_proba(x_test)
predict_proba

array([[0.71865902, 0.28134098],
       [0.97588319, 0.02411681],
       [0.49701339, 0.50298661],
       ...,
       [0.97264184, 0.02735816],
       [0.73341185, 0.26658815],
       [0.38535842, 0.61464158]])

#### Evaluation of logistic regression

In [110]:
from sklearn.metrics import log_loss
LR_Accuracy_Score = metrics.accuracy_score(y_test,predictions)
LR_JaccardIndex = jaccard_score(y_test,predictions)
LR_F1_Score = f1_score(y_test,predictions)
LR_Log_Loss = log_loss(y_test,predictions)

In [115]:
output={"Metrics":["Accuracy Score","Jaccard Score","F1 Score","Log Loss"],"Values":[LR_Accuracy_Score, LR_JaccardIndex, LR_F1_Score, LR_Log_Loss]}
output=pd.DataFrame(output)
output

Metrics    Values
0  Accuracy Score  0.827481
1   Jaccard Score  0.484018
2        F1 Score  0.652308
3        Log Loss  6.218218

#### Modelling for SVM

In [118]:
from sklearn import svm
SVM=svm.SVC(kernel="rbf")
SVM.fit(x_train,y_train)

SVC()

In [120]:
predictions=SVM.predict(x_test)
predictions

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [138]:
SVM_Accuracy_Score = metrics.accuracy_score(y_test,predictions)
SVM_JaccardIndex = jaccard_score(y_test,predictions,pos_label=0)
SVM_F1_Score = f1_score(y_test,predictions,average="weighted")


In [136]:
output={"Metrics":["Accuracy Score","Jaccard Score","F1 Score"],"Values":[SVM_Accuracy_Score, SVM_JaccardIndex, SVM_F1_Score]}
output=pd.DataFrame(output)
output

Metrics    Values
0  Accuracy Score  0.722137
1   Jaccard Score  0.722137
2        F1 Score  0.000000